# Generated by Django 3.0.6 on 2020-06-14 13:16

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancestors', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=list, size=None)),
                ('created_at', models.FloatField(default=0.0)),
                ('content', models.CharField(db_index=True, max_length=480, unique=True)),
                ('hashtag', models.CharField(default='', max_length=15)),
                ('link', models.CharField(default='', max_length=120)),
                ('mention', models.CharField(default='', max_length=15)),
                ('edited_at', models.FloatField(default=0.0)),
                ('mention_seen_at', models.FloatField(default=0.0)),
                ('reply_seen_at', models.FloatField(default=0.0)),
                ('replies', models.IntegerField(db_index=True, default=0)),
                ('saves', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, unique=True)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(default='', max_length=15)),
                ('email', models.CharField(max_length=120, unique=True)),
                ('password', models.CharField(max_length=80)),
                ('remote_addr', models.GenericIPAddressField()),
                ('joined_at', models.FloatField(default=0.0)),
                ('seen_at', models.FloatField(db_index=True, default=0.0)),
                ('emoji', models.CharField(default='', max_length=15)),
                ('country', models.CharField(default='', max_length=2)),
                ('birthyear', models.CharField(default='', max_length=4)),
                ('bio', models.CharField(default='', max_length=120)),
                ('website', models.CharField(default='', max_length=120)),
                ('notif_followers', models.PositiveIntegerField(default=0)),
                ('notif_mentions', models.PositiveIntegerField(default=0)),
                ('notif_replies', models.PositiveIntegerField(default=0)),
                ('saves', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.FloatField(default=0.0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to='app.User')),
                ('to_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='app.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.FloatField(default=0.0)),
                ('seen_at', models.FloatField(default=0.0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='app.User')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='app.User')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='mentioned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentions', to='app.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kids', to='app.Comment'),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('parent', 'created_by')},
        ),
    ]
