# Generated by Django 3.0.6 on 2020-06-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='invited',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(db_index=True, max_length=480, unique=True),
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
