# Generated by Django 3.0.6 on 2020-06-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emoji',
            field=models.CharField(default='', max_length=15),
        ),
    ]
