# Generated by Django 3.0.6 on 2020-06-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.FloatField(default=0.0)),
                ('email', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(default='', max_length=32)),
            ],
        ),
    ]
