# Generated by Django 3.0.6 on 2020-06-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200606_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='saves',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
