# Generated by Django 3.1.3 on 2020-12-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.AlterField(
            model_name='user',
            name='birthyear',
            field=models.CharField(default='', max_length=10),
        ),
    ]
