# Generated by Django 3.0.6 on 2020-06-06 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comment_saves'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('parent', 'created_by')},
        ),
    ]
