# Generated by Django 3.0.6 on 2020-06-06 23:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200606_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ancestors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=list, size=None),
        ),
    ]
