# Generated by Django 3.1.3 on 2020-12-02 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201202_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birthyear',
            new_name='birthday',
        ),
    ]
