# Generated by Django 3.0.6 on 2020-06-07 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200607_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='remote_addr',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.FloatField(default=0.0)),
                ('email', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='app.User')),
                ('invited', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_by', to='app.User')),
            ],
        ),
    ]
