# Generated by Django 3.1.3 on 2021-01-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user_readonly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='readonly',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
