# Generated by Django 3.1.6 on 2021-03-09 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210130_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='replies',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='saves',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notif_followers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notif_mentions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notif_replies',
        ),
        migrations.RemoveField(
            model_name='user',
            name='saves',
        ),
    ]
