# Generated by Django 3.0.6 on 2020-06-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200607_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.FloatField(default=0.0)),
                ('email', models.CharField(max_length=120, unique=True)),
                ('reason', models.CharField(max_length=480)),
            ],
        ),
    ]
