# Generated by Django 3.1.6 on 2021-03-10 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210309_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='ancestors',
        ),
    ]
