# Generated by Django 3.0.6 on 2020-06-07 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verified_at',
        ),
    ]
