# Generated by Django 3.1.6 on 2021-03-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_comment_ancestors'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ancestors',
            field=models.ManyToManyField(related_name='descendants', to='app.Comment'),
        ),
        migrations.AddField(
            model_name='user',
            name='links',
            field=models.JSONField(default=dict),
        ),
    ]
