# Generated by Django 3.0.6 on 2020-06-08 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_user_verified_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='saved_list',
            new_name='saves',
        ),
        migrations.RemoveField(
            model_name='user',
            name='donations',
        ),
        migrations.AlterField(
            model_name='save',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to='app.User'),
        ),
        migrations.AlterField(
            model_name='save',
            name='to_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='app.Comment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='remote_addr',
            field=models.GenericIPAddressField(),
        ),
    ]
