# Generated by Django 3.0.6 on 2020-06-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200608_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='code',
        ),
        migrations.AlterField(
            model_name='user',
            name='seen_at',
            field=models.FloatField(db_index=True, default=0.0),
        ),
    ]
