# Generated by Django 3.1.6 on 2021-03-11 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210310_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='readonly',
        ),
    ]
