# Generated by Django 3.1.6 on 2021-03-13 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_comment_to_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='mentioned',
            new_name='at_user',
        ),
    ]
