# Generated by Django 3.2.6 on 2021-08-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210806_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='remote_addr',
        ),
        migrations.AddField(
            model_name='comment',
            name='agent',
            field=models.CharField(default='', max_length=480),
        ),
    ]
