# Generated by Django 3.2.6 on 2021-09-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210809_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='agent',
            field=models.CharField(default='', max_length=320),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(db_index=True, max_length=640),
        ),
    ]
