# Generated by Django 3.2.6 on 2021-09-19 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210911_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='mention',
        ),
    ]
