# Generated by Django 3.2.6 on 2021-10-06 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20210919_1919'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('emoji', 'first_name', 'last_name')},
        ),
    ]
