# Generated by Django 3.2.8 on 2021-10-16 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_user_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bio',
            new_name='description',
        ),
    ]
