# Generated by Django 4.0.4 on 2022-05-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_rename_ips_article_ids_rename_score_article_readers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
