# Generated by Django 4.0.4 on 2022-05-02 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_user_is_notified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
