# Generated by Django 4.0.4 on 2022-05-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emoji',
            field=models.CharField(default='', max_length=80),
        ),
    ]
