# Generated by Django 4.1 on 2022-08-17 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_user_emoji'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
