# Generated by Django 4.1 on 2022-10-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_delete_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_at', models.FloatField(db_index=True, default=0.0)),
                ('url', models.URLField(max_length=240, unique=True)),
                ('title', models.CharField(max_length=240, unique=True)),
                ('domain', models.CharField(db_index=True, max_length=120)),
                ('author', models.CharField(default='', max_length=120)),
                ('description', models.TextField(default='')),
                ('paragraphs', models.JSONField(default=list)),
                ('ids', models.JSONField(default=list)),
                ('readers', models.IntegerField(db_index=True, default=0)),
            ],
        ),
    ]
