# Generated by Django 4.1.3 on 2022-11-17 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
