# Generated by Django 4.1.3 on 2022-11-24 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_delete_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_notified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='seen_at',
        ),
    ]
