# Generated by Django 4.1.3 on 2022-11-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_remove_user_is_notified_remove_user_seen_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='joined_at',
            new_name='created_at',
        ),
    ]
