# Generated by Django 4.1.3 on 2022-11-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_rename_joined_at_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='link',
            field=models.CharField(default='', max_length=240),
        ),
    ]
