# Generated by Django 4.1.3 on 2022-11-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_comment_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='hashtag',
            field=models.CharField(db_index=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='comment',
            name='link',
            field=models.CharField(db_index=True, default='', max_length=240),
        ),
    ]
