# Generated by Django 4.1.3 on 2022-12-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_comment_hashtag_alter_comment_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='links',
            new_name='social',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet',
            field=models.JSONField(default=dict),
        ),
    ]
