# Generated by Django 4.2.5 on 2024-01-09 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_rename_links_user_social_user_phone_user_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('created_at', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='at_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hashtags', to='app.room'),
        ),
        migrations.AddField(
            model_name='comment',
            name='in_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='app.room'),
        ),
    ]
