# Generated by Django 4.2.5 on 2024-01-09 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_room_comment_at_room_comment_in_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='created_at',
        ),
    ]
