# Generated by Django 4.2.5 on 2024-02-25 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_remove_room_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='hashtag',
        ),
    ]
