# Generated by Django 5.0.6 on 2024-06-19 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_remove_comment_hashtag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Relation',
            new_name='Bond',
        ),
        migrations.RenameModel(
            old_name='Comment',
            new_name='Post',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='app.user'),
        ),
        migrations.AlterField(
            model_name='save',
            name='to_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='app.post'),
        ),
        migrations.RenameField(
            model_name='save',
            old_name='to_comment',
            new_name='post',
        ),
    ]
