# Generated by Django 5.0.6 on 2024-08-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_rename_relation_bond_post_alter_save_to_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hashtag',
            field=models.CharField(db_index=True, default='', max_length=15),
        ),
    ]
