# Generated by Django 5.0.6 on 2024-08-20 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_post_hashtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='at_room',
        ),
        migrations.RemoveField(
            model_name='post',
            name='in_room',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
