# Generated by Django 5.0.6 on 2024-10-01 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_remove_post_at_room_remove_post_in_room_delete_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wallet',
        ),
    ]
