# Generated by Django 5.2.1 on 2025-07-02 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_approved',
        ),
    ]
