# Generated by Django 5.2.1 on 2025-07-16 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0048_remove_user_is_approved"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="at_room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hashtags",
                to="app.room",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="in_room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="threads",
                to="app.room",
            ),
        ),
    ]
