# Generated by Django 5.2.1 on 2025-07-16 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0049_room_post_at_room_post_in_room"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Text",
            new_name="Chat",
        ),
        migrations.RemoveField(
            model_name="post",
            name="hashtag",
        ),
    ]
