# Generated by Django 5.2.1 on 2025-07-17 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0051_post_hashtag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="at_room",
        ),
        migrations.RemoveField(
            model_name="post",
            name="in_room",
        ),
        migrations.DeleteModel(
            name="Room",
        ),
    ]
