# Generated by Django 5.2.1 on 2025-07-18 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0052_remove_post_at_room_remove_post_in_room_delete_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="description",
            field=models.CharField(default="", max_length=240),
        ),
        migrations.AlterField(
            model_name="user",
            name="website",
            field=models.CharField(default="", max_length=240),
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.FloatField(default=0.0)),
                ("edited_at", models.FloatField(default=0.0)),
                ("title", models.CharField(max_length=60)),
                ("entity", models.CharField(max_length=60)),
                ("start_date", models.IntegerField(db_index=True, default=0)),
                ("end_date", models.IntegerField(db_index=True, default=0)),
                ("location", models.CharField(default="", max_length=60)),
                ("link", models.CharField(default="", max_length=240)),
                ("description", models.CharField(default="", max_length=640)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="works",
                        to="app.user",
                    ),
                ),
            ],
        ),
    ]
