# Generated by Django 5.2.1 on 2025-07-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0053_alter_user_description_alter_user_website_work"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="end_date",
            field=models.IntegerField(db_index=True, default=None, null=True),
        ),
    ]
