# Generated by Django 5.2.1 on 2025-07-19 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0054_alter_work_end_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="website",
            new_name="link",
        ),
    ]
