# Generated by Django 5.2.1 on 2025-08-10 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0055_rename_website_user_link"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Work",
        ),
    ]
