# Generated by Django 6.0 on 2026-01-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0056_delete_work"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="seen_at",
            field=models.FloatField(db_index=True, default=0.0),
        ),
    ]
