# Generated by Django 6.0 on 2026-01-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0057_user_seen_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="donations",
            field=models.IntegerField(default=0),
        ),
    ]
