# Generated by Django 6.0 on 2026-01-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0058_user_donations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="donations",
        ),
        migrations.AddField(
            model_name="user",
            name="donated",
            field=models.FloatField(default=0.0),
        ),
    ]
