# Generated by Django 6.0 on 2026-02-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0059_remove_user_donations_user_donated"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="body",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(db_index=True, default="", max_length=240),
        ),
        migrations.AlterField(
            model_name="user",
            name="description",
            field=models.CharField(default="", max_length=640),
        ),
    ]
