# Generated by Django 6.0 on 2026-02-20 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0060_post_body_post_title_alter_user_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="body",
        ),
        migrations.RemoveField(
            model_name="post",
            name="title",
        ),
    ]
