# Generated by Django 6.0.6 on 2026-07-22 16:46

import django.db.models.deletion
from django.db import migrations, models


def deduplicate_push(apps, schema_editor):
    Push = apps.get_model('app', 'Push')
    seen = set()
    to_delete = []
    for p in Push.objects.order_by('user_id', '-created_at'):
        if p.user_id in seen:
            to_delete.append(p.id)
        else:
            seen.add(p.user_id)
    Push.objects.filter(id__in=to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_push'),
    ]

    operations = [
        migrations.RunPython(deduplicate_push, reverse_code=migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='push',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='push',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscription', to='app.user'),
        ),
    ]
