# Generated by Django 6.0.6 on 2026-07-23 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0062_push"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bond",
            unique_together={("created_by", "to_user")},
        ),
    ]
