# Generated by Django 6.0.6 on 2026-07-23 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0063_bond_unique_pair"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="save",
            unique_together={("created_by", "post")},
        ),
    ]
