HEADERS = {
    'User-Agent': "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Safari/605.1.15",
    'Accept': "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
}

FEEDS = [
    "http://feeds.arstechnica.com/arstechnica/index",
    "http://feeds.arstechnica.com/arstechnica/features",
    "http://rss.sciam.com/scientificamerican-global",
    # "http://feeds.reuters.com/news/artsculture",
    # "http://feeds.reuters.com/reuters/businessNews",
    # "http://feeds.reuters.com/reuters/entertainment",
    # "http://feeds.reuters.com/reuters/environment",
    # "http://feeds.reuters.com/reuters/healthNews",
    # "http://feeds.reuters.com/reuters/oddlyEnoughNews",
    # "http://feeds.reuters.com/reuters/scienceNews",
    # "http://feeds.reuters.com/reuters/technologyNews",
    "http://feeds.hbr.org/harvardbusiness/",
    "http://feeds.macrumors.com/macrumors-front",
    "http://feeds.crackberry.com/crackberry/qbtb",
    "http://feeds.imore.com/theiphoneblog",
    "http://feeds.androidcentral.com/androidcentral",
    "http://feeds.windowscentral.com/wmexperts",
    # "http://feeds.feedburner.com/businessinsider",
    "http://feeds.feedburner.com/fubiz",
    "http://feeds.feedburner.com/neowin-main",
    "http://feeds.feedburner.com/petapixel",
    "http://feeds.feedburner.com/thehackersnews",
    "http://feeds.feedburner.com/venturebeat/szyf",
    "http://feeds.feedburner.com/sub/9to5google",
    "http://feeds.feedburner.com/sub/9to5mac",
    "http://feeds.feedburner.com/sub/aeon",
    "http://feeds.feedburner.com/sub/aestheticamagazine",
    "http://feeds.feedburner.com/sub/anandtech",
    "http://feeds.feedburner.com/sub/atlantic",
    "http://feeds.feedburner.com/sub/axios",
    # "http://feeds.feedburner.com/sub/balkaninsight",
    "http://feeds.feedburner.com/sub/berkeley",
    "http://feeds.feedburner.com/sub/bgr",
    "http://feeds.feedburner.com/sub/comingsoon",
    "http://feeds.feedburner.com/sub/dailyartmag",
    "http://feeds.feedburner.com/sub/deepmind",
    "http://feeds.feedburner.com/sub/distill",
    "http://feeds.feedburner.com/sub/eff",
    "http://feeds.feedburner.com/sub/electrek",
    "http://feeds.feedburner.com/sub/endpoints",
    # "http://feeds.feedburner.com/sub/engadget",
    "http://feeds.feedburner.com/sub/fastcompany",
    "http://feeds.feedburner.com/sub/fs",
    "http://feeds.feedburner.com/sub/fubiz",
    "http://feeds.feedburner.com/sub/gsmarena",
    "http://feeds.feedburner.com/sub/karpathy",
    "http://feeds.feedburner.com/sub/kottke",
    "http://feeds.feedburner.com/sub/japantimes",
    "http://feeds.feedburner.com/sub/joshmitteldorf",
    "http://feeds.feedburner.com/sub/increment",
    "http://feeds.feedburner.com/sub/infoq",
    "http://feeds.feedburner.com/sub/lifeextension",
    "http://feeds.feedburner.com/sub/lifespan",
    "http://feeds.feedburner.com/sub/longreads",
    "http://feeds.feedburner.com/sub/massivesci",
    "http://feeds.feedburner.com/sub/mit",
    "http://feeds.feedburner.com/sub/mspoweruser",
    "http://feeds.feedburner.com/sub/nautilus",
    # "http://feeds.feedburner.com/sub/npr",
    "http://feeds.feedburner.com/sub/nytimes/science",
    "http://feeds.feedburner.com/sub/nytimes/tech",
    "http://feeds.feedburner.com/sub/omgubuntu",
    "http://feeds.feedburner.com/sub/peterattia",
    "http://feeds.feedburner.com/sub/polygon",
    "http://feeds.feedburner.com/sub/producthunt",
    "http://feeds.feedburner.com/sub/quantamagazine",
    "http://feeds.feedburner.com/sub/qz",
    "http://feeds.feedburner.com/sub/register",
    "http://feeds.feedburner.com/sub/semiaccurate",
    "http://feeds.feedburner.com/sub/seth",
    "http://feeds.feedburner.com/sub/sixthtone",
    "http://feeds.feedburner.com/sub/smashing",
    # "http://feeds.feedburner.com/sub/techcrunch",
    "http://feeds.feedburner.com/sub/spacenews",
    "http://feeds.feedburner.com/sub/thefreethoughtproject",
    "http://feeds.feedburner.com/sub/thegradient",
    "http://feeds.feedburner.com/sub/tidbits",
    "http://feeds.feedburner.com/sub/verge",
    "http://feeds.feedburner.com/sub/vice",
    "http://feeds.feedburner.com/sub/vox",
    "http://feeds.feedburner.com/sub/wired",
    "http://feeds.feedburner.com/sub/windowslatest"
]
